---
title: "MovieCluster"
output:
  html_document:
    toc: true
    output_dir: "C:/Users/daniel.mois/IdeaProjects/TCC/html"
---

```{r}
rm(list = ls())
```

```{r}
library(NbClust)
library(factoextra)
library(cluster)
library(stringr)
library(ggdendro)
library(dplyr)
library(ggplot2)
library(readr)
library(lubridate)
```

```{r}
movieDatabase = read.csv('C:/Users/daniel.mois/IdeaProjects/TCC/resources/tmdb_5000_movies.csv')
audience = read_delim("C:/Users/daniel.mois/IdeaProjects/TCC/resources/letterboxd.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

```{r}
audience$publicscore = as.numeric(gsub(",",".",audience$publicscore))
```

```{r}
movies = merge(movieDatabase, audience, by="id")
```

```{r}
movies <- movies[complete.cases(movies$publicscore), ]
```

```{r}
which(duplicated(sort(movies$title)))

sort(movieDatabase$title)[439:440]
sort(movieDatabase$title)[2572:2573]
sort(movieDatabase$title)[3800:3801]
```

```{r}
movies = movies[order(movies$title),]
```

```{r}
for (movie in seq_len(length(movies$title)-1)) {
  if (movies$title[movie] == movies$title[movie+1]) {
    movies$title[movie] = paste(movies$title[movie],"-",substr(movies$release_date[movie],1,4))
    movies$title[movie+1] = paste(movies$title[movie+1],"-",substr(movies$release_date[movie+1],1,4))
  }
}
```

```{r}
movies$genres = str_replace(
  str_replace(
    str_replace(
      str_replace(
        str_replace(movies$genres,'\\[','')
        ,'\\]','')
      ,'\\{\"id\": ','')
    ,'\"name\": ','')
  ,'\\}','')
```

```{r}
for (genre in seq_len(length(movies$title)-1)){
  movies$genres[genre] = 
    str_replace(str_replace(strsplit(movies$genres,",")[[genre]][2]," \"",''),"\"",'')
}
```

```{r}
movies = movies[movies$budget > 100000 & movies$revenue > 50000,]
```

```{r}
table(movies$genres)
```

```{r}
movies <- movies %>%
  mutate(across(c("budget","popularity","revenue","runtime","vote_average","publicscore"), as.numeric))
```

```{r}
movies <- movies %>%
  mutate(en_flag = ifelse(original_language == "en", 1, 0))
```

```{r}
movies <- movies %>%
  mutate(decade = 10 * (year(release_date) %/% 10))
```

```{r}
movies <- subset(movies, genres != "Foreign")
```

```{r}
moviesList = split(movies, movies$genres)
```

```{r}
maxmin = function(list) {
  min = min(list)
  max = max(list)
  
  list = (list - min(list))/(max(list) - min(list))
  
  return(list)
}
```

```{r}
moviesList <- lapply(moviesList, function(df) {
  df[, c("budget","popularity","revenue","runtime","vote_average","publicscore","decade")] <- lapply(df[, c("budget","popularity","revenue","runtime","vote_average","publicscore","decade")], maxmin)
  return(df)
})
```

```{r}
normList <- lapply(moviesList, function(df) df[, c("budget","popularity","revenue","runtime","vote_average","publicscore","decade","en_flag")])
```

```{r}
#normList = lapply(normList, function(df) row.names(df) = moviesList$df$id)
```

```{r}
euclidean_distance <- function(df) {
  distances <- dist(df, method = "euclidean")
  return(distances)
}

euclidean_matrix <- function(df) {
  distances <- euclidean_distance(df)
  distancesMatrix <- as.matrix(distances)
  rownames(distancesMatrix) <- colnames(distancesMatrix) <- rownames(df)
  return(distancesMatrix)
}
```

```{r}
distancesMatrix <- lapply(normList, euclidean_matrix)
```

```{r}
distancesList = lapply(normList, euclidean_distance)
```

```{r}
wardList <- vector("list", length = length(distancesList))

for (euc in seq_len(length(distancesList))) {
  
  ward_euc <- hclust(d = distancesList[[euc]], method = "ward.D")
  
    wardList[[paste0("ward.d", euc)]] <- ward_euc
    
}
```

```{r}
#ggdendrogram(wardList$ward.d18, rotate = TRUE, size = 0.5) + theme(text = element_text(size = 8))
```

